name: Notify Discord Webhook when new gh-pages Push

on:
  push:
    branches:
      - gh-pages

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content": "📢 The `gh-pages` branch has been updated!"}' \
               "$DISCORD_WEBHOOK_URL"