name: Discord Webhook Send Message

on:
  push:
    branches:
      - main

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to discord channel
        uses: Chicken-Engine/discord-webhook-github-action@main
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          message: "\* Erererer, we updated the website, you should maybe check it out. I am Sans Undertale."